{{- if .Values.ldap.bindPassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ldapapi-ng.fullname" . }}-ldap
  labels:
    {{- include "ldapapi-ng.labels" . | nindent 4 }}
type: Opaque
stringData:
  LDAP_BIND_PASSWORD: {{ .Values.ldap.bindPassword | quote }}
{{- end }}
