apiVersion: v1
kind: Service
metadata:
  name: {{ include "ldapapi-ng.fullname" . }}
  labels:
    {{- include "ldapapi-ng.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ldapapi-ng.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName }}
      protocol: TCP
